#!/usr/bin/env bash

status() {
    local help_text="Usage: status
Outputs JSON lines of available APIs.
Options:
 -h, --help   Display this help message
"
    if [[ "$1" =~ ^-h|--help$ ]]; then
        echo "$help_text"
        return 0
    fi

    res=$(aws --output json apigateway get-rest-apis | jq -c '.items[] | {id, name,
        created: .createdDate | sub(":[0-9]{2}\\.[0-9]{6}";""),
        type: .endpointConfiguration.types | join(","),
        vpcEndpointIds: (if .endpointConfiguration.vpcEndpointIds then
            .endpointConfiguration.vpcEndpointIds | join(",")
        else
            null
        end)
    }')

    concurrency=32

    task() {
        obj="$1"
        api_id=$(echo "$obj" | jq -r '.id')
        #api_id='53ahy0oiuf'
        ls=$(aws apigateway get-stages --rest-api-id "$api_id" \
            --query 'item' | jq -r 'sort_by(.createdDate) | last | .stageName')
        line=$(jq -c -n --argjson obj "$obj" --arg ls \
            "$ls" '$obj + {latest_stage: $ls}')
        echo "$line" | jq '{id, latest_stage, name, created, type, vpcEndpointIds }'
    }

    (
        #pids=()
        while IFS= read -r obj; do
            ((i = i % concurrency)) # Exits with i. Can't exit on first error
            ((i++ == 0)) && wait
            task "$obj" &
            #pids+=($!)
        done <<<"$res"

        # NOTE: Can't do this and pipe
        # Wait for all backgrounded tasks
        #for pid in "${pids[@]}"; do
        #wait "$pid"
        #done
    )
}
export -f status

url() {
    local help_text="Usage: url <api_id> <stage>
Outputs a single line with the full API URL.
Options:
 -h, --help   Display this help message
"
    if [[ "$1" =~ ^-h|--help$ || -z "$1" || -z "$2" ]]; then
        echo "$help_text"
        return 1
    fi

    api_id="$1"
    stage="$2"
    region=$(aws configure get region)
    echo "https://$api_id.execute-api.$region.amazonaws.com/$stage"
}

stage() {
    local help_text="Usage: stage <api_id> <stage>
Outputs stage details in JSON.
Options:
 -h, --help   Display this help message
"
    if [[ "$1" =~ ^-h|--help$ || -z "$1" || -z "$2" ]]; then
        echo "$help_text"
        return 1
    fi

    api_id="$1"
    stage="$2"

    aws apigateway get-stage --rest-api-id "$api_id" \
        --stage-name "$stage" | jq
}

custom-domains() {
    local help_text="Usage: custom-domains
Outputs custom domain details in JSON lines.
Options:
 -h, --help   Display this help message
"
    if [[ "$1" =~ ^-h|--help$ ]]; then
        echo "$help_text"
        return 0
    fi

    res=$(aws --output json apigateway get-domain-names | jq -c '.items[] | {
        domainName,
        type: (.endpointConfiguration.types | join(",")),
        target: (
            if .endpointConfiguration.types[0] == "REGIONAL" then
                .regionalDomainName
            elif .endpointConfiguration.types[0] == "EDGE" then
                .distributionDomainName
            else
                "unknown type"
            end
        ),
        zoneId: (
            if .endpointConfiguration.types[0] == "REGIONAL" then
                .regionalHostedZoneId
            elif .endpointConfiguration.types[0] == "EDGE" then
                .distributionHostedZoneId
            else
                "unknown type"
            end
        ),
    }')

    concurrency=32

    task() {
        obj="$1"
        domain_name=$(echo "$obj" | jq -r '.domainName')
        api_deets=$(aws --output json apigateway get-base-path-mappings \
            --domain-name "$domain_name" | jq '.items[] ')
        line=$(jq -c -n --argjson obj "$obj" --argjson api_deets "$api_deets" '$obj + $api_deets')
        echo "$line"
    }

    (
        pids=()
        while IFS= read -r obj; do
            ((i = i % concurrency)) # Exits with i. Can't exit on first error
            ((i++ == 0)) && wait
            task "$obj" &
            pids+=($!)
        done <<<"$res"

        # Wait for all backgrounded tasks
        for pid in "${pids[@]}"; do
            wait "$pid"
        done
    )
}
export -f custom-domains

schema() {
    local help_text="Usage: schema <api_id> <stage>
Retrieves the openapi 3 spec for a given API stage, including apigateway extensions.
Options:
 -h, --help   Display this help message
"
    if [[ "$1" =~ ^-h|--help$ || -z "$1" || -z "$2" ]]; then
        echo "$help_text"
        return 1
    fi

    api_id="$1"
    stage="$2"

    aws apigateway get-export \
        --rest-api-id "$api_id" \
        --stage-name "$stage" \
        --export-type "oas30" \
        --parameters extensions='apigateway' \
        --accepts application/json \
        /tmp/schema.json && jq '.' /tmp/schema.json
}

apig() {
    local command="$1"
    shift

    case "$command" in
    status)
        status "$@"
        ;;
    url)
        url "$@"
        ;;
    stage)
        stage "$@"
        ;;
    custom-domains)
        custom-domains "$@"
        ;;
    schema)
        schema "$@"
        ;;
    -h|--help)
        echo "Usage: apig <command> [options]
Commands:
  status         Display list of APIs (Tabular).
  url            Generate API URL.
  stage          Show stage details.
  custom-domains List custom API domains (Tabular).
  schema        Retrieve the openapi 3 spec for an API stage (with apigateway extensions).
"
        ;;
    *)
        echo "Unknown command: $command
Run 'apig --help' for a list of commands."
        return 1
        ;;
    esac
}

apig "$@"
