#!/usr/bin/env bash

# This returns all cfn exports.  It takes an optional argument that filters
# by glob pattern
# E.g:
#	cfn-exports
#	cfn-exports 'subnet'

cmd='aws cloudformation list-exports'

if [ "$#" -ne 0 ]; then
	cmd="${cmd} | jq '.Exports[] | select(.Name|test(\".*${*}.*\"))'"
else
	cmd="${cmd} | jq '.Exports[]'"
fi

eval "$cmd"
