#!/usr/bin/env bash

# This returns all resources deployed by all cfn stacks.  It takes an optional argument
# that defines the level of concurrency.
# E.g:
#	cfn-list-all-stack-resources			# Uses 32 concurrent processes
#	cfn-list-all-stack-resources 4			# Uses  4 concurrent processes

aws cloudformation list-stacks >/tmp/list-stacks.json

concurrency=32

if [ -n "$2" ]; then
	concurrency="$2"
fi

## Parrallel

task() {
	aws cloudformation list-stack-resources --stack-name "$1" |
		jq -c --arg stack_name "$1" '.StackResourceSummaries[] | {StackName: $stack_name, ResourceType, PhysicalResourceId, LogicalResourceId}'
}

stacks=$(jq -r '.StackSummaries[] | select(.StackStatus != "DELETE_COMPLETE") | .StackName' </tmp/list-stacks.json)

(
	for stack_name in ${stacks}; do
		((i = i % concurrency))
		((i++ == 0)) && wait
		#echo "${stack_name}" &
		task "${stack_name}" &
	done
)
