#!/usr/bin/env bash

lambda() {
    local help_text="Usage: ${FUNCNAME[0]} [OPTIONAL_ARGS] [options]
    If no name is provided a list of lambdas is returned.

    Arguments
    lambda_name

    Options:
    -h, --help           Display this help message

    Output:
    jsonlines if no name is provided or structured json if single lambda name provided.

    Examples:
    lambda | grep alert | jtbl
    lambda alert-dev

    "

    # Check if the '--help' or '-h' flag is present
    if [[ "$*" == *"--help"* ]] || [[ "$*" == *"-h"* ]]; then
        echo "$help_text"
        return 0 # Exit the function after printing help
    fi

    # Subcommand: download-link <lambda_name>
    if [ "$1" = "download-link" ]; then
        if [ -z "$2" ]; then
            echo "Error: 'download-link' requires a lambda function name" >&2
            echo "$help_text"
            return 1
        fi
        aws --output text lambda get-function --function-name "$2" --query 'Code.Location'
        return $?
    fi
    
    # No function name: list functions
    if [ -z "$1" ]; then
        aws --output json lambda list-functions | jq -c '.Functions[] | {
            FunctionName, Runtime,
            LastModified,
            LogGroup: .LoggingConfig.LogGroup,
        }'
    else
        aws --output json lambda get-function-configuration --function-name "$1" | jq
    fi
}

lambda "$@"
