#!/usr/bin/env bash

filter_pattern='"*"'

if [ "$#" -ne 0 ]; then
	filter_pattern="$*"
fi

aws codepipeline list-pipelines | jq '.pipelines[].name' | grep "${filter_pattern}" |
	xargs -P20 -n1 -I {} pipeline-check {} | jq -c ' {
		pipelineName, stages: [.stages |
		if all(.status == "Succeeded") then
			.[-1] |
				{status, time}
		elif any(.status == "Failed") then
			.[] | select(.status == "Failed") |
				{status, time: .time?}
		else
			.[] | select(.status != "Succeeded") |
				{status, time}
		end
	]  | .[0]
	}' | jq -c '[.pipelineName, .stages.status, .stages.time?[:19] ]'
