#!/usr/bin/env bash

cmd='aws cloudformation list-exports'

if [ "$#" -ne 0 ]; then
	hz="$1"
	cmd="aws route53 list-hosted-zones | jq --arg hz \"$hz\" '.HostedZones[] \
            | select(.Name == \"$hz\") | .Id' "
else
	cmd="aws route53 list-hosted-zones | jq '.HostedZones[] | .Id' "
fi

#echo "$cmd"
eval "$cmd" | xargs -I {} aws route53 \
	    list-resource-record-sets --hosted-zone-id '{}' \
	    | jq '[.ResourceRecordSets[] | {Name, Type, Target: (.AliasTarget.DNSName? // .ResourceRecords[].Value) }] | group_by(.Name) |
	    map({ Name: .[0].Name, Records: map("\(.Type) \(.Target)") })'
