#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "provide a stack name as the first argument"
	exit 1
fi
stack_name="$1"

stack-events $stack_name 50 | jq '.[] | select(.ResourceStatus|test(".*FAILED")) '
