#!/usr/bin/env bash

#filter_pattern='".*"'

#if [ "$#" -ne 0 ]; then
#filter_pattern="$*"
#fi

#aws cloudformation list-stacks |
#jq -c '.StackSummaries[] | [ .StackName, .StackStatus] ' |
#grep -v 'DELETE' | grep --color=auto "${filter_pattern}"

cmd="aws cloudformation list-stacks | tee /tmp/stack-status.json | \
	jq -c '.StackSummaries[] | [ .StackName, .StackStatus] ' \
	| grep -v 'DELETE_COMPLETE' \
	"

if [ "$#" -ne 0 ]; then
	cmd="${cmd} | grep --color=auto \"$*\" "
fi

eval "$cmd"
