#!/usr/bin/env bash

aws ec2 describe-vpc-endpoint-connections  | jq -c '.VpcEndpointConnections[] |
    select(.VpcEndpointState=="pendingAcceptance") |
        {ServiceId, VpcEndpointId, VpcEndpointState, Tags}' > /tmp/dvec.json


# Loop through each line of the jq output
while IFS= read -r line; do
    # Extract ServiceId and VpcEndpointId using jq
    service_id=$(echo "$line" | jq -r '.ServiceId')
    vpc_endpoint_id=$(echo "$line" | jq -r '.VpcEndpointId')

    # Print the extracted values
    echo "Approving: ServiceId: $service_id, VpcEndpointId: $vpc_endpoint_id"
    aws ec2 accept-vpc-endpoint-connections --service-id "$service_id" \
    --vpc-endpoint-ids "$vpc_endpoint_id" | jq

done < /tmp/dvec.json
